// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: CountFeedFollows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countFeedFollows = `-- name: CountFeedFollows :one
SELECT COUNT(*)
FROM feed_follows
WHERE feed_id = $1
`

func (q *Queries) CountFeedFollows(ctx context.Context, feedID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeedFollows, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
